/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign up with email + password; a confirmation link is emailed */
        post: operations["Auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm the email address and sign in */
        post: operations["Auth_verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email a new confirmation link (always 202) */
        post: operations["Auth_resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in / sign up with a Google ID token */
        post: operations["Auth_google"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in / sign up with a Sign in with Apple identity token */
        post: operations["Auth_apple"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Users_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["Users_updateMyRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Users_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Journals_list"];
        put?: never;
        post: operations["Journals_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["Journals_remove"];
        options?: never;
        head?: never;
        patch: operations["Journals_update"];
        trace?: never;
    };
    "/api/v1/journals/{id}/months/{month}/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Choose the calendar decoration of one month (YYYY-MM) of the journal */
        put: operations["Journals_setMonthTheme"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Journal_list"];
        put?: never;
        post: operations["Journal_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal/sessions/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Journal_suggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Journal_get"];
        put?: never;
        post?: never;
        delete: operations["Journal_remove"];
        options?: never;
        head?: never;
        patch: operations["Journal_update"];
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["Profile_update"];
        trace?: never;
    };
    "/api/v1/profile/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Profile_listInvitations"];
        put?: never;
        /** Invite someone; they receive an email with a link to accept */
        post: operations["Profile_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/invitations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["Profile_removeInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Profile_listSites"];
        put?: never;
        post: operations["Profile_addSite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/sites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["Profile_removeSite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Invitations_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SelfAssignableRole: "ARCHER" | "COACH";
        RegisterDto: {
            /**
             * Format: email
             * @example jane@example.com
             */
            email: string;
            password: string;
            displayName?: string;
            roles: components["schemas"]["SelfAssignableRole"][];
            /**
             * @description Language of the emails sent to the user.
             * @enum {string}
             */
            locale?: "fr" | "en";
        };
        RegistrationDto: {
            /** Format: email */
            email: string;
            /** @description Always true: a confirmation link was emailed; login is refused until it is used. */
            verificationRequired: boolean;
        };
        VerifyEmailDto: {
            /** @description Token from the link emailed at registration. */
            token: string;
            /** @description Human-readable device label (e.g. "Pixel 9", "Firefox on Linux"), shown in session lists. */
            deviceName?: string;
        };
        TokenPairDto: {
            /** @description Short-lived JWT, sent as `Authorization: Bearer <token>`. */
            accessToken: string;
            /** @description Opaque, single-use token exchanged at /auth/refresh for a new pair. */
            refreshToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            /** @description Access token lifetime, in seconds. */
            expiresIn: number;
            /** @description Refresh token lifetime, in seconds. */
            refreshExpiresIn: number;
        };
        ResendVerificationDto: {
            /** Format: email */
            email: string;
        };
        LoginDto: {
            /**
             * Format: email
             * @example jane@example.com
             */
            email: string;
            password: string;
            /** @description Human-readable device label (e.g. "Pixel 9", "Firefox on Linux"), shown in session lists. */
            deviceName?: string;
        };
        SocialSignInDto: {
            /** @description ID token returned by Google Identity Services / Sign in with Apple (web or native SDK). */
            idToken: string;
            /** @description Nonce passed to the provider when requesting the token; checked if present. */
            nonce?: string;
            /** @description Roles for a new account. If omitted for a new account, it is created without roles and the client must ask the user (PUT /users/me/roles). Ignored for existing accounts. */
            roles?: components["schemas"]["SelfAssignableRole"][];
            /** @description Apple only sends the name to the client, on first sign-in: forward it here. */
            displayName?: string;
            /** @enum {string} */
            locale?: "fr" | "en";
            /** @description Human-readable device label (e.g. "Pixel 9", "Firefox on Linux"), shown in session lists. */
            deviceName?: string;
        };
        RefreshTokenDto: {
            refreshToken: string;
        };
        /**
         * @description Empty for an account created through Google / Apple whose user has not chosen yet.
         * @enum {string}
         */
        Role: "ADMIN" | "ARCHER" | "COACH";
        /** @enum {string} */
        AuthProvider: "GOOGLE" | "APPLE";
        UserDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            emailVerified: boolean;
            displayName: string | null;
            /** @example fr */
            locale: string;
            /** @description Empty for an account created through Google / Apple whose user has not chosen yet. */
            roles: components["schemas"]["Role"][];
            /** @description False for accounts created through Google / Apple only. */
            hasPassword: boolean;
            providers: components["schemas"]["AuthProvider"][];
            /** Format: date-time */
            createdAt: string;
        };
        UpdateMyRolesDto: {
            /** @description Replaces the self-assignable roles (ADMIN, if held, is kept). */
            roles: components["schemas"]["SelfAssignableRole"][];
        };
        MonthThemeDto: {
            /**
             * @description Month (YYYY-MM).
             * @example 2026-10
             */
            month: string;
            /**
             * @description Theme id; each client maps it to its own artwork.
             * @example archery
             */
            theme: string;
        };
        JournalDto: {
            /** Format: uuid */
            id: string;
            /** @example Saison 2026-2027 */
            title: string;
            /** @example 2026-09-01 */
            startDate: string;
            /** @example 2027-08-31 */
            endDate: string;
            /** @description Decoration of the calendar, for the months that have one (oldest first). */
            monthThemes: components["schemas"]["MonthThemeDto"][];
            /** @description Number of sessions in the journal. */
            sessionCount: number;
        };
        CreateJournalDto: {
            /** @example Saison 2026-2027 */
            title: string;
            /**
             * @description First day, inclusive (YYYY-MM-DD).
             * @example 2026-09-01
             */
            startDate: string;
            /**
             * @description Last day, inclusive (YYYY-MM-DD). Not before `startDate`.
             * @example 2027-08-31
             */
            endDate: string;
        };
        UpdateJournalDto: {
            /** @example Saison 2026-2027 */
            title?: string;
            /**
             * @description First day, inclusive.
             * @example 2026-09-01
             */
            startDate?: string;
            /**
             * @description Last day, inclusive. The period must keep covering the journal's sessions.
             * @example 2027-08-31
             */
            endDate?: string;
        };
        SetMonthThemeDto: {
            /**
             * @description Theme id, or null to remove the decoration of that month.
             * @example archery
             */
            theme: string | null;
        };
        /** @enum {string} */
        SessionType: "TRAINING" | "COACHING" | "COMPETITION" | "STRENGTH" | "OTHER";
        /** @enum {string} */
        Discipline: "INDOOR" | "TAE_NATIONAL" | "TAE_INTERNATIONAL" | "THREE_D" | "FIELD" | "BEURSAULT" | "RUN_ARCHERY";
        /**
         * @description `OTHER` events only; null = default colour.
         * @enum {string}
         */
        EventColor: "gray" | "red" | "pink" | "grape" | "violet" | "indigo" | "blue" | "cyan" | "teal" | "green" | "lime" | "yellow" | "orange";
        /**
         * @description `OTHER` events only; null = default pictogram.
         * @enum {string}
         */
        EventIcon: "NOTE" | "STAR" | "FLAG" | "TOOL" | "CART" | "USERS" | "CAR" | "MEDICAL" | "GIFT" | "HEART" | "BELL" | "PIN";
        SessionSummaryDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            journalId: string;
            type: components["schemas"]["SessionType"];
            /** @example 2026-10-03 */
            date: string;
            /** @example 18:30 */
            startTime: string | null;
            durationMinutes: number | null;
            location: string | null;
            discipline: components["schemas"]["Discipline"] | null;
            score: number | null;
            /** @description Analyses, or the text of an `OTHER` event. */
            description: string | null;
            /** @description `OTHER` events only. */
            title: string | null;
            /** @description `OTHER` events only; null = default colour. */
            color: components["schemas"]["EventColor"] | null;
            /** @description `OTHER` events only; null = default pictogram. */
            icon: components["schemas"]["EventIcon"] | null;
        };
        SessionSuggestionsDto: {
            locations: string[];
            /** @description Distances in meters. */
            distances: number[];
            wentWell: string[];
            toImprove: string[];
        };
        CreateSessionDto: {
            /**
             * Format: uuid
             * @description Journal the session is added to.
             */
            journalId: string;
            type: components["schemas"]["SessionType"];
            /**
             * @description Local date (YYYY-MM-DD), within the journal's period.
             * @example 2026-10-03
             */
            date: string;
            /**
             * @description Local time (HH:mm); omitted / null = all-day.
             * @example 18:30
             */
            startTime?: string | null;
        };
        /** @enum {string} */
        Feeling: "GREAT" | "OK" | "BAD" | "EXHAUSTED";
        SessionDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            journalId: string;
            type: components["schemas"]["SessionType"];
            /** @example 2026-10-03 */
            date: string;
            /** @example 18:30 */
            startTime: string | null;
            durationMinutes: number | null;
            location: string | null;
            discipline: components["schemas"]["Discipline"] | null;
            score: number | null;
            /** @description Analyses, or the text of an `OTHER` event. */
            description: string | null;
            /** @description `OTHER` events only. */
            title: string | null;
            /** @description `OTHER` events only; null = default colour. */
            color: components["schemas"]["EventColor"] | null;
            /** @description `OTHER` events only; null = default pictogram. */
            icon: components["schemas"]["EventIcon"] | null;
            distanceMeters: number | null;
            arrowCount: number | null;
            objective: string | null;
            satisfaction: number | null;
            technique: number | null;
            physicalFeeling: components["schemas"]["Feeling"] | null;
            mentalFeeling: components["schemas"]["Feeling"] | null;
            wentWell: string[];
            toImprove: string[];
            nextTime: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateSessionDto: {
            type?: components["schemas"]["SessionType"];
            /** @example 2026-10-03 */
            date?: string;
            /** @example 18:30 */
            startTime?: string | null;
            durationMinutes?: number | null;
            location?: string | null;
            discipline?: components["schemas"]["Discipline"] | null;
            distanceMeters?: number | null;
            arrowCount?: number | null;
            score?: number | null;
            objective?: string | null;
            /** @description Overall satisfaction. */
            satisfaction?: number | null;
            /** @description Technique self-assessment. */
            technique?: number | null;
            description?: string | null;
            physicalFeeling?: components["schemas"]["Feeling"] | null;
            mentalFeeling?: components["schemas"]["Feeling"] | null;
            /** @description What went well (≤ 3 lines). */
            wentWell?: string[];
            /** @description What to improve (≤ 3 lines). */
            toImprove?: string[];
            /** @description Notes for the next session. */
            nextTime?: string | null;
            /** @description Title of an `OTHER` event, shown in the calendar. */
            title?: string | null;
            color?: components["schemas"]["EventColor"] | null;
            icon?: components["schemas"]["EventIcon"] | null;
        };
        /** @enum {string} */
        AgeCategory: "U11" | "U13" | "U15" | "U18" | "U21" | "S1" | "S2" | "S3";
        /** @enum {string} */
        BowType: "RECURVE" | "COMPOUND" | "BAREBOW" | "LONGBOW" | "HUNTING" | "FREE";
        ProfileDto: {
            /** @example 0123456A */
            licenceNumber: string | null;
            category: components["schemas"]["AgeCategory"] | null;
            bowType: components["schemas"]["BowType"] | null;
            disciplines: components["schemas"]["Discipline"][];
        };
        UpdateProfileDto: {
            licenceNumber?: string | null;
            category?: components["schemas"]["AgeCategory"] | null;
            bowType?: components["schemas"]["BowType"] | null;
            /** @description Replaces the practised disciplines. */
            disciplines?: components["schemas"]["Discipline"][];
        };
        /** @enum {string} */
        InvitationStatus: "PENDING" | "ACCEPTED";
        InvitationDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            isCoach: boolean;
            status: components["schemas"]["InvitationStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        CreateInvitationDto: {
            /** @example Camille Martin */
            name: string;
            /**
             * Format: email
             * @description Where the invitation is sent.
             */
            email: string;
            /**
             * @description True when the guest is the archer's coach.
             * @default false
             */
            isCoach: boolean;
        };
        SiteDto: {
            /** Format: uuid */
            id: string;
            label: string;
            /** Format: uri */
            url: string;
        };
        CreateSiteDto: {
            /** @example FFTA */
            label: string;
            /**
             * @description http(s) URL.
             * @example https://www.ffta.fr
             */
            url: string;
        };
        AcceptInvitationDto: {
            /** @description Token from the invitation link. */
            token: string;
        };
        AcceptedInvitationDto: {
            /** @description Display name (or email) of the archer who sent the invitation. */
            invitedBy: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example ok
                         * @enum {string}
                         */
                        status?: "ok" | "degraded";
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example error
                         * @enum {string}
                         */
                        status?: "error" | "shutting_down";
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect",
                         *         "responseTime": 3005
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect",
                         *         "responseTime": 3005
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    Auth_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationDto"];
                };
            };
            /** @description EMAIL_TAKEN */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
            /** @description INVALID_VERIFICATION_TOKEN */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
            /** @description INVALID_CREDENTIALS */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description EMAIL_NOT_VERIFIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_google: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialSignInDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
            /** @description INVALID_ID_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description EMAIL_TAKEN (email not verified by the provider) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_apple: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialSignInDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
            /** @description INVALID_ID_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description EMAIL_TAKEN (email not verified by the provider) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
            /** @description INVALID_REFRESH_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Users_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    Users_updateMyRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMyRolesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    Users_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"][];
                };
            };
            /** @description Admins only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Journals_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalDto"][];
                };
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Journals_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJournalDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalDto"];
                };
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Journals_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Journals_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateJournalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalDto"];
                };
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sessions would fall outside the new period */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Journals_setMonthTheme: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                month: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMonthThemeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalDto"];
                };
            };
            /** @description Month outside the journal's period */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Journal_list: {
        parameters: {
            query: {
                /** @description Journal to read. */
                journalId: string;
                /** @description First day, inclusive (YYYY-MM-DD). */
                from: string;
                /** @description Last day, inclusive (YYYY-MM-DD). At most 366 days after `from`. */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryDto"][];
                };
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Journal_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown journal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Journal_suggestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSuggestionsDto"];
                };
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Journal_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Journal_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Journal_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDto"];
                };
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDto"];
                };
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Profile_listInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationDto"][];
                };
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Profile_invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationDto"];
                };
            };
            /** @description CANNOT_INVITE_SELF */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description INVITATION_ALREADY_SENT, LIMIT_REACHED */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Profile_removeInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Profile_listSites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteDto"][];
                };
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Profile_addSite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSiteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteDto"];
                };
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description LIMIT_REACHED */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Profile_removeSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Archers only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Invitations_accept: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedInvitationDto"];
                };
            };
            /** @description INVALID_INVITATION_TOKEN */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
